version: '3.4'

services:

  app:
    build: .
    command: sh -c "python3 project/manage.py migrate && python3 project/manage.py runserver 0.0.0.0:8000"
    volumes:
     - .:/usr/src/app
    container_name: app
    ports:
      - "8000:8000"
        #expose:
        #- "8000"
    hostname: app
    image: app-image
    networks:
      - main
    restart: on-failure
networks:
  main:

