# Generated by Django 4.0.1 on 2022-01-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('file_path_roc', models.TextField(blank=True, null=True)),
                ('file_path_con', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Sai',
            fields=[
                ('upload_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('model_res', models.TextField(blank=True, null=True)),
                ('target_column', models.CharField(max_length=200)),
                ('split_percentage', models.IntegerField(default=50)),
                ('modells', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Sai',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('upload_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('upload_file_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Upload',
            },
        ),
    ]
