# Generated by Django 4.0.1 on 2022-01-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('path_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('models_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Path',
            },
        ),
    ]
