# Generated by Django 4.0.1 on 2022-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Path',
        ),
        migrations.AddField(
            model_name='sai',
            name='models_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
