# Generated by Django 4.0.1 on 2022-01-27 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_path_sai_models_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sai',
            name='target_variable',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
