# Generated by Django 4.0.1 on 2022-02-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sai_target_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rule_data', models.TextField()),
            ],
            options={
                'db_table': 'Segment',
            },
        ),
        migrations.AlterField(
            model_name='sai',
            name='target_variable',
            field=models.CharField(max_length=501),
        ),
    ]
